MVC/Interface/Interface/Controllers/recProductController.cs
using Entities.InterfacesOfRepo;
using Entities.Models;
using Interface.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Interface.Controllers
{
    [Authorize]
    public class recProductController : BaseController
    {
        public recProductController(IUnitOfWork unitOfWork):base(unitOfWork)
        {
            
        }
        
        [HttpGet]
        public IActionResult Index(int skip = 0)
        {
            int id = int.Parse(User.Claims.FirstOrDefault(i => i.Type == ClaimTypes.NameIdentifier).Value);
            ViewBag.Products = IUnitOfWork.Products.FindAll(x => x.ApplicationUserId == id, new string[] { },skip,10).OrderByDescending(x=>x.Id);
            ViewBag.count = IUnitOfWork.Products.Count();
            ViewBag.PageCount = (int)Math.Ceiling((double)ViewBag.Count / 10);
            ViewBag.skip = skip;
            return View();
        }


        public IActionResult fuck(string q)
        {
            int id = int.Parse(User.Claims.FirstOrDefault(i => i.Type == ClaimTypes.NameIdentifier).Value);

            var products = IUnitOfWork.Products.FindAll(x => x.ApplicationUserId == id && x.Name.Contains(q), new string[] { })
                .Select(p => new { id = p.Id, text = p.Name }) 
                .ToList();

            return Json(new { results = products });
        }


        [HttpGet("[Controller]/[action]/{text}")]
        public IActionResult SearchProduct(string text)
        {
            #region code
            int id = int.Parse(User.Claims.FirstOrDefault(i => i.Type == ClaimTypes.NameIdentifier).Value);
            if (text != null)
            {
                ViewBag.Products = IUnitOfWork.Products.FindAll(x => x.ApplicationUserId == id && x.Name.Contains(text), new string[] { }, 0, 10).OrderByDescending(x => x.Id);
            }
            else
            {
                ViewBag.Products = IUnitOfWork.Products.FindAll(x => x.ApplicationUserId == id, new string[] { }, 0, 10).OrderByDescending(x => x.Id);
            }
            ViewBag.count = IUnitOfWork.Products.Count();
            ViewBag.PageCount = (int)Math.Ceiling((double)ViewBag.Count / 10);
            ViewBag.skip = 0; 
            #endregion

            return PartialView("_tablePartial");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(ProductVM vM) 
        {
            if (ModelState.IsValid == true) {
                int id = int.Parse(User.Claims.FirstOrDefault(i => i.Type == ClaimTypes.NameIdentifier).Value);
                Product product = vM.Casting(id);
                IUnitOfWork.Products.Insert(product);
                IUnitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index),vM);
        }

        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            if (id !=0) {
                IUnitOfWork.Products.Delete(IUnitOfWork.Products.GetById(id));
                IUnitOfWork.Save();
            }
            return RedirectToAction(nameof(Index));
        }

        [ValidateAntiForgeryToken]
        public IActionResult DeleteAll ()
        {
            int id = int.Parse(User.Claims.FirstOrDefault(i => i.Type == ClaimTypes.NameIdentifier).Value);
            IUnitOfWork.Products.DeleteAll(x=>x.ApplicationUserId == id);
            IUnitOfWork.Save();
            return RedirectToAction(nameof(Index));
        }


        [Route("[Controller]/[action]/{id}")]
        [HttpGet("[controller]/[action]/{id}")]
        // recProduct/edit/1
        public IActionResult Edit(int id)
        {
            
            return View(IUnitOfWork.Products.GetById(id));

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id,ProductVM vM)
        {
            if (ModelState.IsValid == true)
            {
                Product product = vM.Casting(int.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value));
                product.Id = id;
                IUnitOfWork.Products.UpdateById(product);
                IUnitOfWork.Save();
                return RedirectToAction(nameof(Index));
            }
            return View(vM);

        }
    }
}

MVC/Interface/Interface/Views/recProduct/Edit.cshtml
@using Entities.Models
@model Product

<link rel="stylesheet" href="~/css/afterUserLogin/slider.css">
<link rel="stylesheet" href="~/css/afterUserLogin/products.css">


<div class="container">

    <section class="slider box-content">
        <ul>
            <a asp-action="index" asp-controller="recdash">
            <li>
                <i class="fa-solid fa-gauge"></i>
                Dashboard
            </li>
            </a>
            <a asp-action="index" asp-controller="recproduct">
            <li class="active">
                <i class="fa-solid fa-truck-ramp-box"></i>
                Products
            </li></a>
        </ul>
    </section>
    <section class="main-content ">
        
        <div class="box-content">
            <div class="inside-box">
                <form asp-action="Edit" asp-controller="recProduct" method="post">
                    <div class=" input-fields">
                        <div class="group-content">
                            <label for="">Internal Id</label>
                            <input asp-for="InternalId">
                            <span asp-validation-for="InternalId" style="color:red;margin-bottom:0.2rem"></span>
                        </div>
                        <div class="group-content">
                            <label for="">Name</label>
                            <input asp-for="Name">
                            <span asp-validation-for="Name" style="color:red;margin-bottom:0.2rem"></span>
                        </div>

                        <div class="group-content">
                            <label for="">Unit Price</label>
                            <input type="number" asp-for="UnitPrice">
                            <span asp-validation-for="UnitPrice" style="color:red;margin-bottom:0.2rem"></span>
                        </div>
                        <div class="group-content">
                            <label for="">Unit Type</label>
                            <select name="unittype" id="">
                                <option value="EA">EA</option>
                            </select>
                        </div>
                        <div class="group-content">
                            <label for="">Code</label>
                            <input asp-for="Code">
                            <span asp-validation-for="Code" style="color:red;margin-bottom:0.2rem"></span>
                        </div>
                        <div class="group-content">
                            <label for="">Code Type</label>
                            <select name="codetype" id="">
                                <option value="EGS">EGS</option>
                                <OPTION value="GS1">GS1</OPTION>
                            </select>
                        </div>

                    </div>
                    <div class="group-content">
                        <label for="">Description</label>
                        <textarea asp-for="Description"></textarea>
                        <span asp-validation-for="Description" style="color:red;margin-bottom:0.2rem"></span>
                    </div>
                    <div class="operation">
                        <button type="submit">Update Product</button>
                    </div>
                </form>

            </div>

        </div>
        
    </section>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

MVC/Interface/Interface/Views/recProduct/Index.cshtml
@using Interface.ViewModels
@model ProductVM

<link rel="stylesheet" href="~/css/afterUserLogin/slider.css">
<link rel="stylesheet" href="~/css/afterUserLogin/products.css">


<div class="container">
    
    <section class="slider box-content">
        <ul>
            <a asp-action="index" asp-controller="recdash">
            <li >
                <i class="fa-solid fa-gauge"></i>
                Dashboard
            </li>
            </a>
            <a asp-action="index" asp-controller="recproduct">
            <li class="active">
                <i class="fa-solid fa-truck-ramp-box"></i>
                Products
            </li></a>
        </ul>
    </section>
    <section class="main-content ">
        <div class="box-content btn-operation">
            <form asp-controller="recProduct">
                <button>Insert From EXCEL</button>
                <button type="submit" asp-action="DeleteAll">Delete All</button>
            </form>
        </div>
        <div class="box-content">
            <div class="inside-box">
                <form asp-action="add" asp-controller="recProduct">
                    <div class=" input-fields">
                        <div class="group-content">
                            <label for="">Internal Id</label>
                            <input asp-for="InternalId" >
                            <span asp-validation-for="InternalId" style="color:red;margin-bottom:0.2rem"></span>
                        </div>
                        <div class="group-content">
                            <label for="">Name</label>
                            <input asp-for="Name">
                            <span asp-validation-for="Name" style="color:red;margin-bottom:0.2rem"></span>
                        </div>

                        <div class="group-content">
                            <label for="">Unit Price</label>
                            <input type="number" asp-for="UnitPrice">
                            <span asp-validation-for="UnitPrice" style="color:red;margin-bottom:0.2rem"></span>
                        </div>
                        <div class="group-content">
                            <label for="">Unit Type</label>
                            <select name="unittype" id="">
                                <option value="EA">EA</option>
                            </select>
                        </div>
                        <div class="group-content">
                            <label for="">Code</label>
                            <input asp-for="Code">
                            <span asp-validation-for="Code" style="color:red;margin-bottom:0.2rem"></span>
                        </div>
                        <div class="group-content">
                            <label for="">Code Type</label>
                            <select name="codetype" id="">
                                <option value="EGS">EGS</option>
                                <OPTION value="GS1">GS1</OPTION>
                            </select>
                        </div>

                    </div>
                    <div class="group-content">
                        <label for="">Description</label>
                        <textarea asp-for="Description"></textarea>
                        <span asp-validation-for="Description" style="color:red;margin-bottom:0.2rem"></span>
                    </div>
                    <div class="operation">
                        <button type="submit">Add Product</button>
                    </div>
                </form>
                
            </div>

        </div>

        <div class="box-content">
            <div class="search-box">
                <input type="search" id="txt-search" onchange="getProduct(event)" placeholder="Type to Search for Product..." />
                <i class="fa-solid fa-magnifying-glass"></i>

            </div>

            <partial name="_tablePartial"></partial>



        </div>

    </section>
</div>
        


@section Scripts {

    <script src="~/js/productSearchAjax.js">
        
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}