MVC/Interface/Interface/Controllers/ReceiptsController.cs
using AutoMapper;
using Entities.InterfacesOfRepo;
using Entities.Models;
using Entities.Models.Document;
using Interface.Dto;
using Interface.Dto.ReceiptSubmissions;
using Interface.Dto.ReceiptSubmit;
using Interface.Services;
using Interface.Services.ApiCall;
using Interface.ViewModels;
using Interface.ViewModels.ReceiptVM;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System.Security.Claims;
using System.Text;

namespace Interface.Controllers
{
    [Authorize]
    public class ReceiptsController : BaseController
    {
        #region Constructor
        IWebHostEnvironment env;
        IApiCall api;
        private readonly int userId;
        private readonly IMapper mapper;
        private readonly JsonSerializerSettings jsonSerializer;
        public ReceiptsController(IUnitOfWork unitOfWork,
            IWebHostEnvironment webHostEnvironment,
            IApiCall apiCall,
            IMapper mapper,
            IHttpContextAccessor httpContextAccessor) : base(unitOfWork)
        {
            api = apiCall;
            env = webHostEnvironment;
            this.mapper = mapper;
            userId = int.Parse(httpContextAccessor.HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier).Value);
            jsonSerializer = new JsonSerializerSettings()
            {
                Formatting = Formatting.Indented,
                NullValueHandling = NullValueHandling.Ignore,
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };
        }
        #endregion

        #region Index
        [HttpGet]
        [ServiceFilter(typeof(TokenAttribute))]
        public async Task<IActionResult> Index(int pg = 1,int pageSize = 10)
        {
            string token = HttpContext.Session.GetString("access_token");
            int recsCount = await IUnitOfWork.Receipts.CountAsync(x=>x.ApplicationUserId == userId);
            Pager pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;
            ViewBag.Pager = pager;
            IEnumerable<Receipt> receipts = await IUnitOfWork.Receipts.FindAllAsync(x => x.ApplicationUserId == userId  ,recSkip,pageSize,x=>x.ReceiptId,true);
            if (receipts.Any())
            {
                foreach (Receipt receipt in receipts.Where(x => x.Status == null || x.Status == "InProgress"))
                {
                    ResponseDTO<ReceiptSubmissionsDTO> temp = await api.ReceiptSubmissions<ReceiptSubmissionsDTO>("api/v1/receiptsubmissions", receipt.SubmissionUuid, token);
                    if (temp?.SuccessfulResponse != null)
                    {
                        receipt.Status = temp.SuccessfulResponse.Status;
                    }
                    else if (temp?.ErrorResponse != null)
                    {
                        return RedirectToAction("Index", "Error", temp.ErrorResponse);
                    }
                }
                IUnitOfWork.Receipts.UpdateRange(receipts);
                IUnitOfWork.Save();
            }
            return View(receipts);
        }
        #endregion

        


        #region New
        [HttpGet]
        public IActionResult New()
        {
            var temp = IUnitOfWork.Receipts.FindAll(x => x.ApplicationUserId == userId).OrderByDescending(x => x.ReceiptId).FirstOrDefault();
            if (temp == null)
            {
                return View(new ReceiptVM() { ReceiptNumber = "000001" });
            }
            int lastNum;
            string lastNumber = temp.Header.ReceiptNumber;
            int nextNumber = int.TryParse(lastNumber, out lastNum) ? lastNum + 1 : 0;

            return View(new ReceiptVM() { ReceiptNumber = $"{nextNumber.ToString().PadLeft(6, '0')}" });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ServiceFilter(typeof(TokenAttribute))]
        public async Task<IActionResult> New(ReceiptVM receiptVM)
        {
            if (ModelState.IsValid)
            {
                string token = HttpContext.Session.GetString("access_token");

                ApplicationUser user = await IUnitOfWork.UserManager.FindByIdAsync(userId.ToString());
                Receipt receipt = mapper.Map<Receipt>(user);
                mapper.Map(receiptVM,receipt);
                receipt.Header.Uuid = UuidService.GenerateUUID(receipt);
                if (token != null)
                {
                    ResponseDTO<SuccessfulResponseDTO> subTemp = await api.ReceiptSubmit<SuccessfulResponseDTO>("api/v1/receiptsubmissions", JsonConvert.SerializeObject(
                    new
                    {
                        receipts = new List<Receipt>() { receipt }
                    }, jsonSerializer), token);
                    if (subTemp != null)
                    {
                        if (subTemp.SuccessfulResponse != null)
                        {
                            if (subTemp.SuccessfulResponse.acceptedDocuments?.Count > 0)
                            {
                                receipt.SubmissionUuid = subTemp.SuccessfulResponse.submissionId;
                                await IUnitOfWork.Receipts.AddAsync(receipt);
                                IUnitOfWork.Save();
                                TempData["Message"] = JsonConvert.SerializeObject(new MessageVM() { Icon = "success", Title = "تم الارسال بنجاح.", Message = receipt.SubmissionUuid }) ;
                                return RedirectToAction(nameof(New));
                            }
                            else if (subTemp.SuccessfulResponse.rejectedDocuments?.Count > 0)
                            {
                                List<MessageVM> messageVMs = new List<MessageVM>();
                                foreach (DocumentRejectedDTO dto in subTemp.SuccessfulResponse.rejectedDocuments)
                                {
                                    foreach(StandardErrorDetailsDTO error in dto.error.Details)
                                    {
                                        messageVMs.Add(new MessageVM
                                        {
                                            Icon = "error",
                                            Title = error.Code,
                                            Message = error.Message
                                        });


                                    }
                                }
                                TempData["Message"] = JsonConvert.SerializeObject(messageVMs[0]);

                            }
                        }
                        else if (subTemp.ErrorResponse != null)
                        {
                            if (subTemp.ErrorResponse is StandardErrorResponseDTO errorResponseDTO)
                            {
                                string x;
                            }
                            else if (subTemp.ErrorResponse is SimpleErrorDTO simpleErrorDTO)
                            {
                                TempData["Message"] = JsonConvert.SerializeObject(new MessageVM { Icon = "error", Title = "خطأ", Message = simpleErrorDTO.Error });
                            }
                        }
                    }

                }
                else
                {
                    TempData["Message"] = JsonConvert.SerializeObject(new MessageVM { Icon = "error", Title = "TokenError", Message = "خطأ في الاتصال مع منظومة الايصال الالكتروني" });

                }

            }
            return View(receiptVM);
        }

        #endregion

        #region GetReceiptJson
        [HttpGet]
        public IActionResult GetReceiptJson(int id)
        {
            var receipt = IUnitOfWork.Receipts.FindAll(x => x.ReceiptId == id).FirstOrDefault();
            if (receipt == null)
            {
                return NotFound();
            }
            var json = JsonConvert.SerializeObject(receipt, jsonSerializer);
            return File(Encoding.UTF8.GetBytes(json), "application/json", $"{receipt.SubmissionUuid}.json");
        }
        #endregion

        #region Details
        [HttpGet]
        [ServiceFilter(typeof(TokenAttribute))]
        public async Task<IActionResult> Details(string Id)
        {
            string token = HttpContext.Session.GetString("access_token");

            ResponseDTO<ReceiptSubmissionsDTO> temp = await api.ReceiptSubmissions<ReceiptSubmissionsDTO>("api/v1/receiptsubmissions", Id, token);
            if (temp != null)
            {
                if (temp.SuccessfulResponse != null && temp.SuccessfulResponse.Status == "Invalid")
                {
                    foreach (DocumentSummaryDTO documentSummaryDTO in temp.SuccessfulResponse.Receipts)
                    {
                        foreach (DocumentSummaryErrorsDTO documentSummaryErrorsDTO in documentSummaryDTO.Errors)
                        {
                            foreach(InnerErrorDTO innerErrorDTO in documentSummaryErrorsDTO.Error.InnerError)
                            {
                                ModelState.AddModelError("", innerErrorDTO.ErrorAr);
                            }
                        }
                    }
                }
                else if (temp.ErrorResponse != null)
                {
                    if (temp.ErrorResponse is StandardErrorResponseDTO errorResponseDTO)
                    {
                        string x;
                    }
                    else if (temp.ErrorResponse is SimpleErrorDTO simpleErrorDTO)
                    {
                        TempData["Message"] = JsonConvert.SerializeObject(new MessageVM { Icon = "error", Title = "خطأ", Message = simpleErrorDTO.Error });
                    }
                }
            }
            Receipt receipt = IUnitOfWork.Receipts.FindAll(x => x.SubmissionUuid == Id).FirstOrDefault();

MVC/Interface/Interface/Views/Receipts/Details.cshtml
@using Entities.Models.Document
@using Entities.Models.Document.BaseComponent
@model Receipt
@{
    ViewBag.Title = "NOTE Solution - Details";
}
<div class="d-flex flex-column gap-3" dir="rtl">
    <div class="box ">
        <div class=" row row-cols-md-2 row-cols-sm-1">
            <div class="w-100">
                @{
                    if(Model.Status == "Valid")
                    {
                        <div>
                            <p class="fs-3 text-success">
                                @(@Model.DocumentType.ReceiptType == "S" ? "ايصال بيع" : "ايصال مرتجع")
                                <i class="fa-solid fa-circle-check"></i>
                            </p>
                        </div>
                    }
                    else if (Model.Status == "Invalid")
                    {
                        <div >
                            <p class="fs-3 text-danger">
                                @(@Model.DocumentType.ReceiptType == "S" ? "ايصال بيع" : "ايصال مرتجع")
                                <i class="fa-solid fa-triangle-exclamation"></i>
                            </p>
                        </div>
                    }
                    else
                    {
                        <h4>@(@Model.DocumentType.ReceiptType == "S" ? "ايصال بيع" : "ايصال مرتجع")</h4>
                    }
                }
            </div>
            <div class="form-group">
                <label style="font-weight:bold">رقم الايصال</label>
                <p class="form-control">@Model.Header.ReceiptNumber</p>
            </div>
            <div class="form-group">
                <label style="font-weight:bold">تاريخ الايصال</label>
                <p class="form-control">@Model.Header.DateTimeIssued</p>
            </div>
            <div class="form-group w-100">
                <label style="font-weight:bold">معرف الايصال</label>
                <p class="form-control overflow-auto">@Model.Header.Uuid</p>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header d-flex justify-content-between">
            <h3 >بيانات الممول</h3>
        </div>
        <div class="row row-cols-lg-4 row-cols-md-2 row-cols-sm-1">
            <div class="form-group">
                <label style="font-weight:bold">اسم الشركة</label>
                <p class="form-control">@Model.Seller.CompanyTradeName</p>
            </div>
            <div class="form-group">
                <label style="font-weight:bold">رقم تسجيل</label>
                <p class="form-control">@Model.Seller.Rin</p>
            </div>
            <div class="form-group">
                <label style="font-weight:bold">رقم تسجيل</label>
                <p class="form-control">@Model.Seller.ActivityCode</p>
            </div>
            <div class="form-group">
                <label style="font-weight:bold">العنوان</label>
                <p class="form-control">@(@Model.Seller.BranchAddress.BuildingNumber),@(Model.Seller.BranchAddress.Street),@(Model.Seller.BranchAddress.Governate),@(Model.Seller.BranchAddress.Country)</p>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header d-flex justify-content-between">
            <h3 >بيانات العميل</h3>
        </div>
        <div class="row row-cols-lg-4 row-cols-md-2 row-cols-sm-1">
            <div class="form-group">
                <label style="font-weight:bold">اسم العميل</label>
                <p class="form-control">@Model.Buyer.Name</p>
            </div>
            @if(Model.Buyer.Id!= null)
            {
                <div class="form-group">
                    <label style="font-weight:bold">معرف العميل</label>
                    <p class="form-control">@Model.Buyer.Id</p>
                </div>
            }
            @if(Model.Buyer.MobileNumber != null)
            {
                <div class="form-group">
                    <label style="font-weight:bold">رقم تليفون</label>
                    <p class="form-control">@Model.Buyer.MobileNumber</p>
                </div>
            }
            <div class="form-group">
                <label style="font-weight:bold">نوع</label>
                <p class="form-control">@(Model.Buyer.Type == "P" ? "شخص" : Model.Buyer.Type == "B" ? "شركة" : "اجنبي")</p>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header d-flex justify-content-between">
            <h3>بنود الايصال</h3>
        </div>
        <div class="overflow-auto">
            <table class="styled-table">
                <thead >
                    <tr>
                        <th class="col-1">كود الداخلي</th>
                        <th class="col-5">وصف المنتج</th>
                        <th class="col-1">سعر الوحدة</th>
                        <th class="col-1">كمية</th>
                        <th class="col-2">خصم</th>
                        <th class="col-2">ضريبة</th>
                    </tr>
                </thead>
                <tbody class="">
                    @foreach (Item item in Model.ItemData)
                    {
                        <tr>

                            <td>@item.InternalCode</td>
                            <td>@item.Description</td>
                            <td>@item.UnitPrice</td>
                            <td>@item.Quantity</td>
                            <td>@item.CommercialDiscountData.Select(x => x.Amount).FirstOrDefault()</td>
                            <td>@item.TaxableItems.Select(x => x.Amount).Sum()</td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4"></td>
                        <th colspan="1">اجمالي المبيعات : </th>
                        <td>@Model.TotalSales</td>
                    </tr>
                    <tr>
                        <td colspan="4"></td>

                        <th>اجمالي الخصم : </th>
                        <td>@Model.TotalCommercialDiscount</td>

                    </tr>
                    <tr>
                        <td colspan="4"></td>

                        <th>اجمالي الضريبة : </th>
                        <td></td>

                    </tr>
                    <tr>
                        <td colspan="4"></td>
                        <th>اجمالي المبلغ : </th>
                        <td>@Model.TotalAmount</td>

                    </tr>

                </tfoot>
            </table>
        </div>
    </div>
    <div asp-validation-summary="All" class="text-danger" style="font-weight:bold;font-size:1.2rem">
    </div>
</div>

MVC/Interface/Interface/Views/Receipts/New.cshtml
@using Interface.ViewModels.ReceiptVM
@using Newtonsoft.Json

@model ReceiptVM

@{
    ViewBag.Title = "NOTE Solution - New Receipt";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@@ttskch/select2-bootstrap4-theme/dist/select2-bootstrap4.min.css">

<form asp-controller="Receipts" asp-action="New" method="post" onsubmit="SweetAlert.confirm(event,'هل تريد الارسال؟','','question')" class="d-flex flex-column gap-3" dir="rtl">
    
    <div class="box">
        <div class="box-header d-flex justify-content-between">
            <h3>معلومات اساسية</h3>
        </div>
        
        <div class="row row-cols-lg-4 row-cols-md-2 row-cols-sm-1">
            <div class="form-group mb-2">
                <label class="">رقم الايصال<span class="text-danger">*</span></label>
                <input type="text" id="ReceiptNumber" name="ReceiptNumber" value="@Model.ReceiptNumber" class="form-control" />
                <span asp-validation-for="ReceiptNumber" class="text-danger"></span>
            </div>
            <div class="form-group mb-2 ">
                <label>تاريخ<span class="text-danger">*</span></label>
                <input type="datetime-local" class="form-control" asp-for="DateTime">
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
            <div class="form-group mb-2 ">
                <label>نوع<span class="text-danger">*</span></label>
                <select asp-for="Type" class="form-select">
                    <option value="S">ايصال جديد</option>
                    <option value="R">ايصال مرتجع</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group mb-2 ">
                <label>اصدار<span class="text-danger">*</span></label>
                <select asp-for="Version" class="form-select">
                    <option value="1.2">1.2</option>
                </select>
                <span asp-validation-for="Version" class="text-danger"></span>
            </div>
            <div class="form-group mb-2">
                <label>طريقة الدفع<span class="text-danger">*</span></label>
                <select asp-for="PaymentMethod" class="form-select">
                    <option selected value="C">Cash</option>
                    <option value="V">Visa</option>
                </select>
                <span asp-validation-for="PaymentMethod" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-header d-flex justify-content-between">
            <h3>معلومات العميل</h3>
        </div>
        <div class="row row-cols-lg-4 row-cols-md-2 row-cols-sm-1">
            <div class="form-group mb-2 ">
                <label>اسم العميل<span class="text-danger">*</span></label>
                <input type="text" class="form-control" asp-for="IssuedName">
                <span asp-validation-for="IssuedName" class="text-danger"></span>
            </div>
            <div class="form-group mb-2 ">
                <label>نوع العميل<span class="text-danger">*</span></label>
                <select asp-for="IssuedType" class="form-select">
                    <option value="P">شخص</option>
                    <option value="B">شركة</option>
                    <option value="F">اجنبي</option>
                </select>
                <span asp-validation-for="IssuedType" class="text-danger"></span>
            </div>
            <div class="form-group mb-2 ">
                <label>رقم تعريفي</label>
                <input type="text" class="form-control" asp-for="IssuedNumber">
                <span asp-validation-for="IssuedNumber" class="text-danger"></span>
            </div>
            <div class="form-group mb-2 ">
                <label>رقم تليفون</label>
                <input type="text" class="form-control" asp-for="IssuedPhone">
                <span asp-validation-for="IssuedPhone" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="box">
        <div class="box-header d-flex justify-content-between">
            <h3 >بندود الايصال</h3>
            
        </div>
        <div class="overflow-auto" dir="rtl">
            <table class="styled-table">
                <thead>
                    <tr>
                        <th class="col-2">كود الداخلي</th>
                        <th class="col-3">وصف المنتج</th>
                        <th hidden>ItemType</th>
                        <th hidden>ItemCode</th>
                        <th hidden>UnitType</th>
                        <th class="col-1">كمية</th>
                        <th class="col-1">سعر الوحدة</th>
                        <th class="col-1">خصم</th>
                        <th hidden>NetSale</th>
                        <th hidden>TotalSale</th>
                        <th hidden>Total</th>
                        <th class="col-1">ضريبة</th>
                        <th class="col-1"></th>

                    </tr>
                </thead>
                <tbody id="table_item_body">
                    @for (int i = 0; i < Model?.itemData?.Count(); i++)
                    {

                        <tr>
                            <td><input class="form-control" name="itemData[@i].InternalCode" value="@Model.itemData[i].InternalCode" /></td>
                            <td><input class="form-control" name="itemData[@i].Description" value="@Model.itemData[i].Description" /></td>
                            <td hidden><input class="form-control" name="itemData[@i].ItemType" value="@Model.itemData[i].ItemType" /></td>
                            <td hidden><input class="form-control" name="itemData[@i].ItemCode" value="@Model.itemData[i].ItemCode" /></td>
                            <td hidden><input class="form-control" name="itemData[@i].UnitType" value="@Model.itemData[i].UnitType" /></td>
                            <td><input class="form-control" name="itemData[@i].Quantity" value="@Model.itemData[i].Quantity" /></td>
                            <td><input class="form-control" name="itemData[@i].UnitPrice" value="@Model.itemData[i].UnitPrice" /></td>
                            <td><input class="form-control" name="itemData[@i].CommercialDiscountData" value="@(JsonConvert.SerializeObject(Model.itemData[i].CommercialDiscountData))" /></td>
                            <td hidden><input class="form-control" name="itemData[@i].NetSale" value="@Model.itemData[i].NetSale" /></td>
                            <td hidden><input class="form-control" name="itemData[@i].TotalSale" value="@Model.itemData[i].TotalSale" /></td>
                            <td hidden><input class="form-control" name="itemData[@i].Total" value="@Model.itemData[i].Total" /></td>
                            <td><input class="form-control" name="itemData[@i].TaxableItems" value="@(JsonConvert.SerializeObject(Model.itemData[i].TaxableItems))" /></td>
                            <td>
                                <button type="button" onClick="Page.deleteRow(event.target)" class="btn btn-danger">حذف</button>
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th colspan="6"></th>
                        <th>
                            <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                اضافة بند جديد
                            </button>
                        </th>
                    </tr>
                </tfoot>
            </table>

            
        </div>
        

    </div>
    <div class="box">
        <div class="row row-cols-lg-4">
            <div class="form-group">
                <label>اجمالي الضريبة</label>
                <input asp-for="TotalCommercialDiscount" class="form-control" />
            </div>
            <div class="form-group">
                <label>اجمالي المبيعات</label>
                <input asp-for="TotalSales" class="form-control" />
            </div>
            <div>
                <label>الاجمالي بعد الضريبة</label>
                <input asp-for="NetAmount" class="form-control" />
            </div>
            <div>
                <label>الاجمالي</label>
                <input asp-for="TotalAmount" class="form-control" />
            </div>
            <div class="d-none">
                <label>الضريبة</label>
                <input asp-for="TaxTotals" class="form-control" />
            </div>
        </div>
    </div>





    <span asp-validation-for="itemData" class="text-danger"></span>
    <div class="text-start">
        <button type="button" id="saveBtn" class="btn btn-success ">
            حفظ بدون ارسال
            <i class="fa-regular fa-floppy-disk"></i>
        </button>
        <input type="submit" class="btn btn-primary" value="حفظ وارسال">

    </div>


</form>

<div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" dir="rtl">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
        <div class="modal-content" >
            <div class="modal-body">
                <div class="d-flex flex-column gap-2" id="itemArea">

                    <div class=" row row-cols-md-2 row-cols-sm-1">
                        <div class="form-group ">
                            <label>اسم المنتج</label>
                            <select class="form-control" data-live-search="true" id="ProductName">
                            </select>
                            <span class="text-danger"></span>
                        </div>
                        <div class=" form-group">
                            <label>سعر الوحدة</label>
                            <input type="number" id="UnitPrice" class="form-control">
                            <span class="text-danger"></span>
                        </div>
                        <div class="form-group ">
                            <label>كمية</label>
                            <input type="number" id="Quantity" class="form-control  ">
                            <span class="text-danger"></span>
                        </div>
                        <div class=" form-group  ">
                            <label>خصم</label>
                            <input type="number" id="Discount" class="form-control  ">
                            <span class="text-danger"></span>
                        </div>
                        <div class="form-group w-100">
                            <label>وصف المنتج</label>
                            <textarea id="Description" class="form-control"></textarea>
                            <span class="text-danger"></span>
                        </div>
                    </div>
                    <div id="taxArea">
                        
                        
                        <table class="styled-table">
                            <thead>
                                <tr>
                                    <th class="col-4">نوع الضريبة</th>
                                    <th class="col-4">تفاصيل الضريبة</th>
                                    <th class="col-2">نسبة</th>
                                    <th class="col-2">قيمة</th>
                                    <th class="col text-start"></th>
                                </tr>
                            </thead>
                            <tbody id="itemTaxTable"></tbody>
                        </table>
                        <div class="form-group text-start">
                            <button type="button" id="addTaxBtn" class=" btn btn-success ">اضافة ضريبة</button>
                        </div>
                    </div>
                    <div>
                        <div class="row row-cols-md-2 row-cols-sm-1">
                            <div class="form-group">
                                <label>الاجمالي بدون خصم و ضريبة</label>
                                <input id="itemTotalSale" class="form-control mb-2" type="number" disabled />
                            </div>
                            <div class="form-group">
                                <label>الجمالي بعد الخصم</label>
                                <input id="itemNetSale" class="form-control mb-2" type="number" disabled />
                            </div>
                            <div class="form-group">
                                <label>اجمالي الضريبة</label>
                                <input id="itemTotalTax" class="form-control mb-2" type="number" disabled />
                            </div>
                            <div class="form-group">
                                <label>اجمالي بعد الضريبة والخصم</label>
                                <input id="itemTotal" class="form-control mb-2" type="number" disabled />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">اغلاق</button>
                <button type="button" id="addItemBtn" class="btn btn-primary">
                    اضافة البند
                    <i class="fa-solid fa-plus"></i>
                </button>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="~/js/Receipt/Classes.js"></script>

    <script type="module" src="~/js/Receipt/New.js">
    </script>

    


    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }


}